import React from 'react'

import {
  faAws,
  faReact,
  faVuejs,
  faDocker,
  faHtml5,
  faCss3Alt,
  faSass,
  faPhp,
  faSquareJs,
  faPython,
  faWordpress,
  faShopify,
  faLaravel,
  faGoogle,
  faGithub,
  faGitAlt,
  faTwitter,
  faInstagram,
  faFigma,
  faApple,
  faSlack,
  faWindows,
  faNode,
  faMicrosoft,
} from '@fortawesome/free-brands-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export const ICON_BRANDS_DATA = {
  aws: <FontAwesomeIcon icon={faAws} />,
  react: <FontAwesomeIcon icon={faReact} />,
  html5: <FontAwesomeIcon icon={faHtml5} />,
  vue: <FontAwesomeIcon icon={faVuejs} />,
  css3: <FontAwesomeIcon icon={faCss3Alt} />,
  sass: <FontAwesomeIcon icon={faSass} />,
  docker: <FontAwesomeIcon icon={faDocker} />,
  php: <FontAwesomeIcon icon={faPhp} />,
  python: <FontAwesomeIcon icon={faPython} />,
  shopify: <FontAwesomeIcon icon={faShopify} />,
  wordpress: <FontAwesomeIcon icon={faWordpress} />,
  javascript: <FontAwesomeIcon icon={faSquareJs} />,
  laravel: <FontAwesomeIcon icon={faLaravel} />,
  gitHub: <FontAwesomeIcon icon={faGithub} />,
  google: <FontAwesomeIcon icon={faGoogle} />,
  git: <FontAwesomeIcon icon={faGitAlt} />,
  twitter: <FontAwesomeIcon icon={faTwitter} />,
  instagram: <FontAwesomeIcon icon={faInstagram} />,
  figma: <FontAwesomeIcon icon={faFigma} />,
  apple: <FontAwesomeIcon icon={faApple} />,
  slack: <FontAwesomeIcon icon={faSlack} />,
  windows: <FontAwesomeIcon icon={faWindows} />,
  nodeJs: <FontAwesomeIcon icon={faNode} />,
  microsoft: <FontAwesomeIcon icon={faMicrosoft} />,
}