// Scope descriptions based on the work recorded in ProjectData.
export const SKILL_CONTEXTS: Record<string, string> = {
  "React": "画面・フォームの実装、既存UIの改修",
  "TypeScript": "型定義の整備、any型の解消",
  "Next.js": "既存サイトの移行、画面開発",
  "Vue 3": "画面統合、コンポーネント・状態管理の設計",
  "HTML5": "画面のマークアップ・スタイリング",
  "CSS3": "画面のマークアップ・スタイリング",
  "Sass": "画面のマークアップ・スタイリング",
  "SCSS": "画面のマークアップ・スタイリング",
  "JavaScript": "画面機能の実装・改修",
  "jQuery": "既存画面の保守・改修",
  "Shopify": "Liquidによる独自デザイン・機能実装",
  "WordPress": "CMSの学習・個人制作",
  "GraphQL": "API開発、フロントエンドとの連携",
  "Apollo Client": "GraphQL APIとのデータ連携",
  "React Hook Form": "フォーム実装、入力検証・エラー表示",
  "React Router": "画面のルーティング",
  "Storybook": "画面の自動テスト、コンポーネント管理",
  "Jest": "ユニットテストの実装・テスト環境整備",
  "Playwright": "E2Eテストの実装・保守",
  "Chakra UI": "UIコンポーネントを用いた画面開発",
  "MUI": "UIコンポーネントを用いた画面開発",
  "Radix UI": "UIコンポーネントを用いた画面開発",
  "Vuetify": "UIコンポーネントを用いた画面開発",
  "Node.js": "バックエンド開発での利用",
  "NestJS": "GraphQL APIの開発・保守",
  "TypeORM": "API開発でのデータベース連携",
  "PostgreSQL": "既存のデータベース環境での開発",
  "Amazon DynamoDB": "既存のデータベース環境での開発",
  "Docker": "開発環境での利用",
  "Linux": "開発環境での利用",
  "GCP": "開発環境での利用",
  "WSL": "開発環境での利用",
  "AWS": "AWS環境でのフロントエンド開発・保守",
  "AWS Amplify": "Amplify環境での保守開発",
  "Ruby on Rails": "バックエンドの学習・個人開発",
  "Laravel": "バックエンドの学習・個人開発",
  "Python 3": "スクリプト・開発ツール",
  "Google Apps Script": "業務の自動化",
  "Visual Studio Code": "日々のコーディング",
  "Figma": "デザイン仕様の確認・実装連携",
  "Adobe XD": "デザイン仕様の確認・実装連携",
  "Illustrator": "画像・素材の編集",
  "Adobe Photoshop": "画像・素材の編集",
  "webpack": "ビルド環境の利用・設定",
  "gulp": "ビルド環境の利用・設定",
  "Backlog": "タスク・進捗管理",
  "Asana": "タスク・進捗管理",
  "Jira": "タスク・進捗管理",
  "Git": "ソース管理・コードレビュー",
  "GitHub": "ソース管理・コードレビュー",
  "Google Spreadsheet": "業務情報の整理・管理",
  "Windows": "日常の開発環境",
  "macOS": "日常の開発環境",
  "Claude": "コード調査・実装、設計書・コードのレビュー",
  "Codex": "コード調査・実装・リファクタリング・レビュー",
  "ChatGPT": "技術調査・設計検討・情報整理",
  "Gemini": "開発時のAI支援",
  "基本設計・詳細設計": "画面設計、試験観点の整理",
  "Design Doc": "画面構成・状態管理・ライブラリ選定の方針整理",
  "IAM / RBAC": "ロール・権限モデル、認可制御の設計・実装",
  "試験設計・テスト自動化": "試験観点の作成、UI・E2Eテスト整備",
  "AIコード・設計レビュー": "設計書・コードの事前確認、レビュー観点の明文化"
}
